[package]
name = "opensearch"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }

[dependencies]
opensearch-dsl = { path = "../opensearch-dsl/" }

bytes = "1.5.0"
futures-util = "0.3.29"
futures = "0.3.29"
percent-encoding = "2.3.0"
regress = "0.7.1"
reqwest = { version = "0.11.22", default-features = false, features = [
    "json",
    "stream",
    "gzip",
    "native-tls",
] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
serde_urlencoded = "0.7.1"
tracing = "0.1.40"
thiserror = "1.0.50"
derive_builder = "0.12.0"
# client stuff
base64 = "0.21.5"
task-local-extensions = "0.1.4"
reqwest-middleware = "0.2.4"
reqwest-retry = "0.3.0"
reqwest-tracing = "0.4.6"
anyhow = "1.0.75"
async-trait = "0.1.74"
url = "2.4.1"
# miette = "5.10.0"
walkdir = { version = "2.4.0", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
http-cache-reqwest = "0.12.0"

[features]
default = [
    "cat",
    "cluster",
    "indices",
    "ingest",
    "nodes",
    "ml",
    "mtermvectors",
    "remote",
    "security",
    "snapshot",
    "tasks",
    "tools",
]
cat = []
cluster = []
indices = []
ingest = []
nodes = []
mtermvectors = []
ml = []
remote = []
security = []
snapshot = []
tasks = []
# custom features
tools = ["indices", "ingest", "dep:walkdir", "ml"]
