[package]
name = "opensearch-client"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# request
tracing-opentelemetry = "0.21.0"
opentelemetry = "0.20.0"
http-cache-reqwest = "0.11.1"
reqwest = { version = "0.11.20", features = ["json"] }
reqwest-middleware = "0.2.3"
reqwest-retry = "0.3.0"
reqwest-tracing = { version = "0.4.6", features = ["opentelemetry_0_19"] }
# async
futures-util = "0.3.28"
futures = "0.3.28"

# general
chrono = { version = "0.4.26", features = ["serde"] }
derive_builder = "0.12.0"
strum = { version = "0.25.0", features = ["derive"] }
rayon = { version = "1.7.0" }

# tracing
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = [
  "json",
  "time",
  "env-filter",
] }
# json
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# error
thiserror = "1.0.40"
anyhow="*"

[dev-dependencies]
# test
testcontainers = "0.14.0"
