[package]
name = "opensearch"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }

[dependencies]
bytes = "1.5.0"
futures-core = "0.3.28"
futures="*"
percent-encoding = "2.3.0"
regress = "0.7.1"
reqwest = { version = "0.11.20", default-features = false, features = ["json", "stream"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
serde_urlencoded = "0.7.1"

