[package]
name = "opensearch-testcontainer"
description = "Testcontainer for OpenSearch"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true
repository.workspace = true
keywords = [
    "docker",
    "testcontainers",
    "testcontainer",
    "opensearch",
    "integration-test",
]
readme.workspace = true

[dependencies]
testcontainers = "0.15.0"

[dev-dependencies]
reqwest = { version = "0.12.3", features = ["blocking"] }
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
