[package]
name = "opensearch-dsl"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }

[dependencies]
chrono = { version = "0.4.31", default-features = false, features = ["std", "serde"] }
num-traits = "0.2.17"
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.107", features = ["raw_value"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
