[package]
name = "opensearch-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opensearch = { path = "../opensearch-client/" }
opensearch-dsl = { path = "../opensearch-dsl/" }
clap = { version = "4.4.7", features = ["derive", "env"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.0"
anyhow = "1.0.75"
tokio = { version = "1.33.0", features = ["full"] }
url = "2.4.1"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
async-compression ={version = "*", features = ["tokio", "zstd"] }
futures="*"