[package]
name = "opensearch-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opensearch-client = { workspace = true, features = [
    "search",
    "indices",
    "tools",
] }
opensearch-dsl = { workspace = true }
clap = { version = "4.5.21", features = ["derive", "env"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
anyhow = "1.0.93"
tokio = { version = "1.41.1", features = ["full"] }
url = "2.5.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
async-compression = { version = "0.4.17", features = ["tokio", "zstd"] }
futures = "0.3.31"
